<?php

/**
 * @file
 * Contains media_entity_libsyn.module.
 */

/**
 * Implements hook_theme().
 */
function media_entity_libsyn_theme($existing, $type, $theme, $path) {
  return [
    'media_libsyn_embed' => [
      'variables' => [
        'episode_id' => NULL,
        'width' => NULL,
        'height' => NULL,
        'theme' => NULL,
        'custom-color' => NULL,
        'direction' => NULL,
        'options' => [],
      ],
      'file' => 'media_entity_libsyn.theme.inc',
    ]
  ];
}
