media_entity_libsyn.settings:
  type: config_object
  label: 'Media entity Libsyn settings'
  mapping:
    thumbnail_destination:
      type: string
      label: 'Destination for thumbnails'

media.source.libsyn:
  type: media.source.field_aware
  label: 'Libsyn type configuration'

field.formatter.settings.libsyn_embed:
  type: mapping
  label: 'Field display format settings'
  mapping:
    width:
      type: string
      label: 'Width'
    height:
      type: string
      label: 'Height'
    theme:
      type: string
      label: 'Theme'
    custom_color:
      type: string
      label: 'Custom color'
    direction:
      type: string
      label: 'Direction'
    options:
      type: mapping
      label: 'Options'
      mapping:
        autonext:
          type: string
          label: 'Auto next'
        thumbnail:
          type: string
          label: 'Show thumbnail'
        autoplay:
          type: string
          label: 'Autoplay'
        preload:
          type: string
          label: 'Preload'
        no_addthis:
          type: string
          label: 'No Addthis'
        render_playlist:
          type: string
          label: 'Render playlist'
